/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module "@vue/runtime-core" {
	export interface GlobalComponents {
		CommonBar: typeof import("./src/components/CommonBar.vue")["default"];
		CommonContent: typeof import("./src/components/CommonContent.vue")["default"];
		NAffix: typeof import("naive-ui")["NAffix"];
		NButton: typeof import("naive-ui")["NButton"];
		NIcon: typeof import("naive-ui")["NIcon"];
		RouterLink: typeof import("vue-router")["RouterLink"];
		RouterView: typeof import("vue-router")["RouterView"];
	}
}
